import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ background:'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', minHeight: '100vh',
          margin: 0,
          padding: 0,
          backgroundAttachment: 'fixed',
          backgroundSize: 'cover'}}
      >
      <Providers>{children}</Providers>
      </body>
    </html>
  );
}
